version: '3'
services:
  db: # Database implementation, in this case MySQL
    image: mysql:5.7
    container_name: seek-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file:
      - docker/db.env
    volumes:
      - seek-mysql-db:/var/lib/mysql

  seek: # The SEEK application
    #build: .
    image: fairdom/seek:master
    container_name: seek
    command: docker/entrypoint.sh
    restart: always
    environment:
      RAILS_ENV: production
      SOLR_PORT: 8983
      SOLR_HOST: solr
      NO_ENTRYPOINT_WORKERS: 1
    env_file:
      - docker/db.env
    volumes:
      - seek-filestore:/seek/filestore
      - seek-cache:/seek/tmp/cache
    ports:
      - "3000:3000"
    depends_on:
      - db
      - solr
      - virtuoso
    links:
      - db
      - solr
      - virtuoso

  seek_workers: # The SEEK delayed job workers
    #build: .
    image: fairdom/seek:master
    container_name: seek-workers
    command: docker/start_workers.sh
    restart: always
    environment:
      RAILS_ENV: production
      SOLR_PORT: 8983
      SOLR_HOST: solr
      DBA_PASSWORD: wibble
      VIRTUOSO: 'true'
    env_file:
      - docker/db.env
    volumes:
      - seek-filestore:/seek/filestore
      - seek-cache:/seek/tmp/cache
    depends_on:
      - db
      - solr
      - virtuoso
    links:
      - db
      - solr
      - virtuoso

  solr:
    image: fairdom/seek-solr:8.11
    container_name: seek-solr
    restart: always
    environment:
      SOLR_JAVA_MEM: -Xms512m -Xmx1024m
    volumes:
      - seek-solr-data:/var/solr/
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - seek
      - /opt/solr/server/solr/configsets/seek_config 

  virtuoso:
    image: tenforce/virtuoso
    container_name: seek-virtuoso
    restart: always
    ports:
      - "8890:8890"
      - "1111:1111"
    environment:
      DBA_PASSWORD: wibble
    volumes:
      - seek-virtuoso-data:/data


volumes:
  seek-filestore:
  seek-mysql-db:
  seek-solr-data:
  seek-cache:
  seek-virtuoso-data:
