experimental_assay_class:
  id: 1
  title: <%= I18n.t('assays.experimental_assay') %>
  key: EXP

modelling_assay_class:
  id: 2
  title: <%= I18n.t('assays.modelling_analysis') %>
  key: MODEL

modelling_assay_class:
  id: 2
  title: <%= I18n.t('assays.informatics_analysis') %>
  key: INF