
assay types:
  title: assay types
  children: experimental_assay_type, modelling_analysis_type
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#AssayType

experimental_assay_type:
  title: experimental assay type
  children: genomics,metabolomics,proteomics,single-cell,transcriptomics, fluxomics, reactomics, interactomics, organism_or_strain_characterisation
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#ExperimentalAssayType

fluxomics:
  title: fluxomics
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#fluxomics

genomics:
  title: genomics
  children: comparative_genomics,DNA_sequencing,genotyping,next_generation_sequencing_analsysis,primer_design,SNP_detection,amplification
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#genomics

comparative_genomics: 
  title: comparative genomics
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#comparative genomics

DNA_sequencing:
  title: DNA sequencing
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#DNA_sequencing

genotyping:
  title: genotyping
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#genotyping

next_generation_sequencing_analysis:
  title: next generation sequence analysis
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Next_generation_sequencing_analysis

primer_design:
  title: primer design
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#primer_design

SNP_detection:
  title: SNP detection
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#SNP_detection

amplification:
  title: amplification
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Amplification

#---------------------------
metabolomics:
  title: metabolomics
  children: metabolite_profiling,metabonomics
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#metabolomics

cell_growth_optimisation:
  title: cell growth optimisation
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#cell_growth_optimisation

metabolite_profiling:
  title: metabolite profiling
  children: catabolic_response,glucose_pulse, flux_balance_analysis, metabolite_concentration
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#metabolite_profiling

flux_balance_analysis:
  title: flux balance analysis
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#flux_balance_analysis

catabolic_response:
  title: catabolic response
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#catabolic_response

glucose_pulse:
  title: glucose pulse
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#glucose_pulse

metabolite_concentration:
  title: Metabolite concentration
  children: extracellular_metabolite_concentration, intracellular_metabolite_concentration
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Metabolite_concentration

extracellular_metabolite_concentration:
  title: Extracellular metabolite concentration
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Extracellular_metabolite_concentration

intracellular_metabolite_concentration:
  title: Intracellular metabolite concentration
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Intracellular_metabolite_concentration

metabonomics:
  title: metabonomics
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#metabonomics

organism_or_strain_characterisation:
  title: organism or strain characterisation
  children: by_project_formation, cell_growth_rate, cell_size, limited_media_growth, substract_utilization
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Organism_or_strain_characterisation

by_product_formation:
  title: by-product formation
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#By-production_formation

cell_growth_rate:
  title: cell growth rate
  children: cell_growth_optimisation
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Cell_growth_rate

cell_size:
  title: cell size
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Cell_size

limited_media_growth:
  title: limited media growth
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Limited_media_growth

substrate_utilization:
  title: substrate utilization
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Substrate_utilization

interactomics:
  title: interactomics
  children: protein_protein_interaction_profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Interactomics

protein_protein_interaction_profiling:
  title: protein-protein interaction profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Protein-protein_interaction_profiling

#-------------------------------

proteomics:
  title: proteomics
  children: immune_precipitation,post-translational_modification,protein-protein_interaction,protein_expression_profiling,protein_identification,protein_structural_analysis
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#proteomics

immune_precipitation:
  title: immune precipitation
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#immune_precipitation

post-translational_modification:
  title: post-translational modification
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#post-translational_modification

protein-protein_interaction:
  title: protein-protein interaction
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#protein-protein_interaction

protein_expression_profiling:
  title: protein expression profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#protein_expression_profiling

protein_identification:
  title: protein identification
  children: protein_purification
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#protein_identification

protein_purification:
  title: protein purification
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#protein_purification

protein_structural_analysis:
  title: protein structural analysis
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#protein_structural_analysis

#----------------------------------

single_cell:
  title: single cell
  children: FRAP
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Single_cell

#-----------------------------------

transcriptomics:
  title: transcriptomics
  children: Comparative_genomic_hybridization,gene_expression_profiling,methylation_profiling,microRNA_profiling,rna_seq_profiling,RNAi,tiling_path
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#transcriptomics

Comparative_genomic_hybridization:
  title: Comparative genomic hybridization
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Comparative_genomic_hybridization

gene_expression_profiling:
  title: gene expression profiling
  children: cDNA_microarray,transcriptional_profiling,translational_profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#gene_expression_profiling

#cDNA_microarray:
#  title: cDNA microarray
#  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#

transcriptional_profiling:
  title: transcriptional profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#transcriptional_profiling

translational_profiling:
  title: translational profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#translational_profiling

methylation_profiling:
  title: methylation profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#methylation_profiling

microRNA_profiling:
  title: microRNA profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#microRNA_profiling

rna_seq_profiling:
  title: RNA-seq profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#RNA-seq_profiling

RNAi:
  title: RNAi
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#RNAi

tiling_path:
  title: tiling path
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#tiling_path


modelling_analysis_type:
  title: modelling analysis type
  children: cell_cycle,enzymology,gene_expression,gene_regulatory_network,metabolic_network,metabolism,signal_transduction,translation, genome_scale
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#ModelAnalysisType

cell_cycle:
  title: cell cycle
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#cell_cycle

enzymology:
  title: enzymology
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#enzymology

gene_expression:
  title: gene expression
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#gene_expression

gene_regulatory_network:
  title: gene regulatory network
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#gene_regulatory_network

metabolic_network:
  title: metabolic network
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#metabolic_network

metabolism:
  title: metabolism
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#metabolism

signal_transduction:
  title: signal transduction
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#signal_transduction

translation:
  title: translation
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#translation

protein_interations:
  title: protein interactions
genome_scale:
  title: genome scale
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Genome_scale

#--------
reactomics:
  title: reactomics
  children: single_cell, enzymatic, genome_scale_enzyme_activity_profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#protein_interactions

enzymatic:
  title: enzymatic
  children: continuous_enzymatic, discontinuous_enzymatic
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Enzymatic_assay

genome_scale_enzyme_activity_profiling:
  title: genome-scale enzyme activity profiling
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Genome-scale_enzyme_activity_profiling

continuous_enzymatic:
  title: continuous enzymatic
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Continuous_enzymatic

discontinuous_enzymatic:
  title: discontinuous enzymatic
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Discontinuous_enzymatic
