# Needed as normally the types are Seeded.
Journal:
  title: Journal
  key: article

Book:
  title: Book
  key: book

Booklet:
  title: Booklet
  key: booklet

InBook:
  title: InBook
  key: inbook

InCollection:
  title: InCollection
  key: incollection

InProceedings:
  title: InProceedings
  key: inproceedings

Manual:
  title: Manual
  key: manual

BachelorThesis:
  title: Bachelor's Thesis
  key: bachelorsthesis

MastersThesis:
  title: Master's Thesis
  key: mastersthesis

DiplomaThesis:
  title: Diplom Thesis
  key: diplomthesis

Misc:
  title: Misc
  key: misc

PhdThesis:
  title: Doctoral Thesis
  key: phdthesis

Proceedings:
  title: Proceedings
  key: proceedings

Techreport:
  title: Tech report
  key: techreport

Unpublished:
  title: Unpublished
  key: unpublished