# -------------------------------------------------------------------
#  Mapped legacy SEEK Types  â†’  New DataCite Types
#  Based on DataCite Metadata Schema Documentation
#  https://datacite-metadata-schema.readthedocs.io/en/4.6/appendices/appendix-1/resourceTypeGeneral/#
# -------------------------------------------------------------------

JournalArticle:
  title: Journal Article
  key: journalarticle   # was: article (Journal)

Book:
  title: Book
  key: book

Booklet:
  title: Booklet
  key: booklet

BookChapter:
  title: Book Chapter
  key: bookchapter       # was: InBook (inbook)

Collection:
  title: Collection
  key: collection        # was: InCollection (incollection)

ConferencePaper:
  title: Conference Paper
  key: conferencepaper   # was: InProceedings (inproceedings)

ConferenceProceeding:
  title: Conference Proceeding
  key: conferenceproceeding   # was: Proceedings

Text:
  title: Text
  key: text              # was: Manual (manual)

BachelorThesis:
  title: Bachelor's Thesis
  key: bachelorsthesis

MastersThesis:
  title: Master's Thesis
  key: mastersthesis

DiplomaThesis:
  title: Diplom Thesis
  key: diplomthesis

PhdThesis:
  title: Doctoral Thesis
  key: phdthesis

Other:
  title: Other
  key: other              # replaces Misc

Preprint:
  title: Preprint
  key: preprint           # was: Unpublished

Report:
  title: Report
  key: report             # was: Tech report

# -------------------------------------------------------------------
#  Additional Extended DataCite Types
# -------------------------------------------------------------------

Audiovisual:
  title: Audiovisual
  key: audiovisual

Award:
  title: Award
  key: award

ComputationalNotebook:
  title: Computational Notebook
  key: computationalnotebook

DataPaper:
  title: Data Paper
  key: datapaper

Dataset:
  title: Dataset
  key: dataset

Event:
  title: Event
  key: event

Image:
  title: Image
  key: image

Instrument:
  title: Instrument
  key: instrument

InteractiveResource:
  title: Interactive Resource
  key: interactiveresource

Model:
  title: Model
  key: model

OutputManagementPlan:
  title: Output Management Plan
  key: outputmanagementplan

PeerReview:
  title: Peer Review
  key: peerreview

PhysicalObject:
  title: Physical Object
  key: physicalobject

Project:
  title: Project
  key: project

Service:
  title: Service
  key: service

Software:
  title: Software
  key: software

Sound:
  title: Sound
  key: sound

Standard:
  title: Standard
  key: standard

StudyRegistration:
  title: Study Registration
  key: studyregistration

Workflow:
  title: Workflow
  key: workflow

ProjectDeliverable:
  title: Project Deliverable
  key: projectdeliverable