# See the explanation in faceted_browsing.yml

#isa
Assay:
  organism:
      label: Organism
      value_from: organisms:title
  human_diseases:
      label: Human Disease
      value_from: human_diseases:title
  assay_type:
      label: Assay Type
      value_from: assay_type_label
      facet_class: Exhibit.HierarchicalFacet
      tree_from: Seek::Ontologies::AssayTypeReader,Seek::Ontologies::ModellingAnalysisTypeReader
  technology_type:
      label: Technology Type
      value_from: technology_type_label
      facet_class: Exhibit.HierarchicalFacet
      tree_from: Seek::Ontologies::TechnologyTypeReader

#assets
DataFile:
  assay_type:
        label: Assay Type
        value_from: assay_type_titles
        facet_class: Exhibit.HierarchicalFacet
        tree_from: Seek::Ontologies::AssayTypeReader,Seek::Ontologies::ModellingAnalysisTypeReader
  technology_type:
        label: Technology Type
        value_from: technology_type_titles
        facet_class: Exhibit.HierarchicalFacet
        tree_from: Seek::Ontologies::TechnologyTypeReader

Model:
  organism:
      label: Organism
      value_from: organism:title
  human_disease:
      label: Human Disease
      value_from: human_disease:title
  model_type:
      label: Model Type
      value_from: model_type:title
  model_format:
      label: Model Format
      value_from: model_format:title
  recommended_environment:
      label: Execution or Visualization Environment
      value_from: recommended_environment:title
  modelling_analysis_type:
      label: Modelling Analysis Type
      value_from: assay_type_titles
      facet_class: Exhibit.HierarchicalFacet
      tree_from: Seek::Ontologies::ModellingAnalysisTypeReader

Sop:
  technology_type:
        label: Technology Type
        value_from: technology_type_titles
        facet_class: Exhibit.HierarchicalFacet
        tree_from: Seek::Ontologies::TechnologyTypeReader
  assay_type:
        label: Assay Type
        value_from: assay_type_titles
        facet_class: Exhibit.HierarchicalFacet
        tree_from: Seek::Ontologies::AssayTypeReader,Seek::Ontologies::ModellingAnalysisTypeReader

Publication:
  author:
      label: Author
      value_from: publication_author_names
  published_year:
      label: Published Year
      value_from: published_date:year
  organism:
      label: Organism
      value_from: related_organisms:title
  human_disease:
      label: Human Disease
      value_from: related_human_diseases:title

#yellow pages
Person:
  discipline:
      label: Discipline
      value_from: disciplines:title
  expertise:
      label: Expertise
      value_from: expertise:text
  tool:
      label: Tool
      value_from: tools:text
  role:
      label: Role
      value_from: project_positions:title
  institution:
      label: Institution
      value_from: institutions:title
  location:
      label: Location
      value_from: locations
  name:
      label: Name
      value_from: name

Project:
  name:
      label: Name
      value_from: title
  organism:
      label: Organism
      value_from: organisms:title
  human_disease:
      label: Human Disease
      value_from: human_diseases:title
  institution:
      label: Institution
      value_from: institutions:title
  location:
      label: Location
      value_from: locations

Institution:
  name:
      label: Name
      value_from: title
  location:
      label: Location
      value_from: country

Programme:
  name:
      label: Name
      value_from: title

#biosamples
Strain:
  organism:
      label: Organism
      value_from: organism:title
  human_disease:
      label: Human Disease
      value_from: human_disease:title
  gene:
      label: Modified Gene
      value_from: genotypes:gene:title

Event:
  start_date:
      label: Event date
      value_from: start_date:year
  country:
      label: Country
      value_from: country
