refresh: 'famfamfam_silk/arrow_refresh_small.png' 
arrow_up: 'famfamfam_silk/arrow_up.png' 
arrow_down: 'famfamfam_silk/arrow_down.png' 
arrow_right: 'famfamfam_silk/arrow_right.png' 
next: 'famfamfam_silk/arrow_right.png' 
arrow_left: 'famfamfam_silk/arrow_left.png' 
back: 'famfamfam_silk/arrow_left.png' 
arrow_down_small: 'misc_icons/arrow_down_small.png' 
bioportal_logo: 'logos/bioportal_logo.png' 
new: 'famfamfam_silk/add.png' 
add: 'famfamfam_silk/add.png' 
multi_add: 'famfamfam_silk/table_add.png' 
download: 'crystal_project/16x16/actions/build.png' 
big_download: 'crystal_project/32x32/actions/build.png' 
show: 'famfamfam_silk/zoom.png' 
zoom_in: 'famfamfam_silk/zoom_in.png' 
zoom_out: 'famfamfam_silk/zoom_out.png' 
copy: 'famfamfam_silk/page_copy.png' 
edit: 'famfamfam_silk/page_white_edit.png' 
edit_off: 'stop_edit.png' 
manage: 'famfamfam_silk/wrench.png' 
destroy: 'famfamfam_silk/cross.png' 
tag: 'famfamfam_silk/tag_blue.png' 
favourite: 'famfamfam_silk/star.png' 
comment: 'famfamfam_silk/comment.png' 
comments: 'famfamfam_silk/comments.png' 
info: 'famfamfam_silk/information.png' 
help: 'famfamfam_silk/help.png' 
confirm: 'famfamfam_silk/accept.png' 
reject: 'famfamfam_silk/cancel.png' 
user: 'famfamfam_silk/user.png' 
person: 'famfamfam_silk/user.png' 
avatar: 'famfamfam_silk/picture.png' 
avatars: 'famfamfam_silk/photos.png' 
save: 'famfamfam_silk/disk.png' 
message: 'famfamfam_silk/email.png' 
message_read: 'famfamfam_silk/email_open.png' 
reply: 'famfamfam_silk/email_go.png' 
message_delete: 'famfamfam_silk/email_delete.png' 
messages_outbox: 'famfamfam_silk/email_go.png' 
file: 'redmond_studio/documents_16.png' 
logout: 'famfamfam_silk/door_out.png' 
login: 'famfamfam_silk/door_in.png' 
picture: 'famfamfam_silk/picture.png' 
pictures: 'famfamfam_silk/photos.png' 
profile: 'famfamfam_silk/user_suit.png' 
history: 'famfamfam_silk/time.png' 
news: 'famfamfam_silk/newspaper.png' 
announcement: 'famfamfam_silk/transmit.png' 
denied: 'famfamfam_silk/exclamation.png' 
institution: 'famfamfam_silk/house.png' 
project: 'famfamfam_silk/report.png' 
tick: 'crystal_project/22x22/apps/clean.png' 
lock: 'famfamfam_silk/lock.png' 
open: 'famfamfam_silk/lock_open.png' 
no_user: 'famfamfam_silk/link_break.png' 
sop: 'famfamfam_silk/page.png' 
sops: 'famfamfam_silk/page_copy.png' 
model: 'crystal_project/32x32/apps/kformula.png' 
models: 'crystal_project/64x64/apps/kformula.png' 
data_file: 'famfamfam_silk/database.png' 
data_files: 'famfamfam_silk/database.png' 
study: 'famfamfam_silk/page.png' 
test: 'crystal_project/16x16/actions/run.png' 
execute: 'famfamfam_silk/lightning.png' 
warning: 'crystal_project/22x22/apps/alert.png' 
warn: 'crystal_project/22x22/apps/alert.png' 
skipped: 'crystal_project/22x22/actions/undo.png' 
error: 'famfamfam_silk/exclamation.png' 
feedback: 'famfamfam_silk/email.png' 
spinner: 'ajax-loader.gif' 
large_spinner: 'ajax-loader-large.gif' 
current: 'famfamfam_silk/bullet_green.png' 
collapse: 'folds/fold.png' 
expand: 'folds/unfold.png' 
pal: 'famfamfam_silk/rosette.png' 
admin: 'famfamfam_silk/shield.png' 

#files
pdf_file: 'file_icons/small/pdf.png'
xls_file: 'file_icons/small/xls.png' 
doc_file: 'file_icons/small/doc.png' 
misc_file: 'file_icons/small/genericBlue.png' 
ppt_file: 'file_icons/small/ppt.png' 
xml_file: 'file_icons/small/xml.png' 
zip_file: 'file_icons/small/zip.png' 
jpg_file: 'file_icons/small/jpg.png' 
gif_file: 'file_icons/small/gif.png' 
png_file: 'file_icons/small/png.png' 
jpg_file: 'file_icons/small/jpg.png' 
bmp_file: 'file_icons/small/bmp.png' 
svg_file: 'file_icons/small/svg.png' 
txt_file: 'file_icons/small/txt.png' 
rtf_file: 'file_icons/small/rtf.png' 
html_file: 'file_icons/small/html.png'


investigation_avatar: 'crystal_project/64x64/apps/mydocuments.png' 
investigation: 'crystal_project/64x64/apps/mydocuments.png' 
investigations: 'crystal_project/64x64/apps/mydocuments.png' 
study_avatar: 'crystal_project/64x64/apps/package_editors.png' 
assay_avatar: 'misc_icons/flask3-64x64.png' 
assay_experimental_avatar: 'misc_icons/flask3-64x64.png' 
assay: 'misc_icons/flask3-64x64.png' 
assay_modelling_avatar: 'crystal_project/64x64/filesystems/desktop.png' 
model_avatar: 'crystal_project/64x64/apps/kformula.png' 
person_avatar: 'avatar.png' 
jerm_logo: 'jerm_logo.png' 
project_avatar: 'project_64x64.png' 
institution_avatar: 'institution_64x64.png' 
programme_avatar: 'crystal_project/64x64/filesystems/folder_favorites.png' 
organism_avatar: 'misc_icons/cell3.png' 
strain_avatar: 'misc_icons/enterococcus_faecalis64-64.jpg' 
publication_avatar: 'crystal_project/64x64/mimetypes/wordprocessing.png' 
publication: 'crystal_project/64x64/mimetypes/wordprocessing.png' 
publications: 'crystal_project/64x64/mimetypes/wordprocessing.png' 
saved_search_avatar: 'crystal_project/32x32/actions/find.png' 
saved_search: 'crystal_project/32x32/actions/find.png' 
visit_pubmed: 'famfamfam_silk/page_white_go.png' 
markup: 'famfamfam_silk/page_white_text.png' 
atom_feed: 'misc_icons/feed_icon.png' 
impersonate: 'famfamfam_silk/group_go.png' 
partial_world: 'misc_icons/partial_world.png' 
world: 'famfamfam_silk/world.png' 
file_large: 'crystal_project/32x32/apps/klaptop.png' 
internet_large: 'crystal_project/32x32/devices/Globe2.png' 
jws_builder: 'misc_icons/jws_builder24x24.png' 
event_avatar: 'crystal_project/32x32/apps/vcalendar.png' 
specimen_avatar: 'misc_icons/green_virus-64x64.png' 
sample_avatar: 'misc_icons/sampleBGXblue.png' 
specimen: 'misc_icons/green_virus-64x64.png' 
specimens: 'misc_icons/green_virus-64x64.png' 
publish: 'famfamfam_silk/world_add.png' 
spreadsheet: 'famfamfam_silk/table.png' 
spreadsheet_annotation: 'famfamfam_silk/tag_blue.png' 
spreadsheet_annotation_edit: 'famfamfam_silk/tag_blue_edit.png' 
spreadsheet_annotation_add: 'famfamfam_silk/tag_blue_add.png' 
spreadsheet_annotation_destroy: 'famfamfam_silk/tag_blue_delete.png' 
spreadsheet_export: 'famfamfam_silk/table_go.png' 
unsubscribe: 'famfamfam_silk/email_delete.png' 
subscribe: 'famfamfam_silk/email_add.png' 
presentation_avatar: 'misc_icons/1315482798_presentation-slides.png' 
presentation: 'misc_icons/1315482798_presentation-slides.png' 
presentations: 'misc_icons/1315482798_presentation-slides.png' 
endnote: 'famfamfam_silk/script_go.png' 
expand_plus: 'toggle_expand_64x64.png' 
collapse_minus: 'toggle_collapse_64x64.png' 
cytoscape_web: 'famfamfam_silk/chart_line.png' 
graph: 'famfamfam_silk/chart_line.png' 
import: 'famfamfam_silk/page_add.png' 
project_manager: 'famfamfam_silk/medal_gold_1.png' 
asset_manager: 'famfamfam_silk/medal_bronze_3.png' 
gatekeeper: 'famfamfam_silk/medal_silver_2.png' 
organise: 'famfamfam_silk/folder.png' 
search: 'famfamfam_silk/eye.png' 
report: 'famfamfam_silk/report.png' 
jws_shadow: 'jws/shadow2.gif' 
home: 'famfamfam_silk/house.png' 
waiting: 'misc_icons/waiting.png' 
run_workflow: 'famfamfam_silk/cog_go.png' 
workflow_avatar: 'logos/taverna_logo.png' 
sweep: 'famfamfam_silk/chart_organisation.png' 
share: 'famfamfam_silk/link.png' 
sweep_run: 'famfamfam_silk/table_multiple.png' 
simple_run: 'famfamfam_silk/table.png' 
myexperiment: 'myexp_icon.png' 
filter: 'crystal_project/16x16/actions/filter.png'

 #add file icons via script
aac_file: 'file_icons/small/aac.png'
aif_file: 'file_icons/small/aif.png'
ai_file: 'file_icons/small/ai.png'
asp_file: 'file_icons/small/asp.png'
aspx_file: 'file_icons/small/aspx.png'
avi_file: 'file_icons/small/avi.png'
bin_file: 'file_icons/small/bin.png'
css_file: 'file_icons/small/css.png'
db_file: 'file_icons/small/db.png'
dll2_file: 'file_icons/small/dll2.png'
dll_file: 'file_icons/small/dll.png'
eps_file: 'file_icons/small/eps.png'
exe1_file: 'file_icons/small/exe1.png'
exe2_file: 'file_icons/small/exe2.png'
fav_file: 'file_icons/small/fav.png'
genericOrange_file: 'file_icons/small/genericOrange.png'
genericRed_file: 'file_icons/small/genericRed.png'
genericTurquesa_file: 'file_icons/small/genericTurquesa.png'
gz_file: 'file_icons/small/gz.png'
help2_file: 'file_icons/small/help2.png'
help_file: 'file_icons/small/help.png'
hqx_file: 'file_icons/small/hqx.png'
htmlFirefox_file: 'file_icons/small/htmlFirefox.png'
htmlIE_file: 'file_icons/small/htmlIE.png'
htmlSafari1_file: 'file_icons/small/htmlSafari1.png'
htmlSafari2_file: 'file_icons/small/htmlSafari2.png'
js_file: 'file_icons/small/js.png'
mov2_file: 'file_icons/small/mov2.png'
mov_file: 'file_icons/small/mov.png'
mp2_file: 'file_icons/small/mp2.png'
mp3_file: 'file_icons/small/mp3.png'
mp4_file: 'file_icons/small/mp4.png'
mpg_file: 'file_icons/small/mpg.png'
php_file: 'file_icons/small/php.png'
pic_file: 'file_icons/small/pic.png'
pps_file: 'file_icons/small/pps.png'
psd_file: 'file_icons/small/psd.png'
rar_file: 'file_icons/small/rar.png'
rb_file: 'file_icons/small/rb.png'
tif_file: 'file_icons/small/tif.png'
ttf_file: 'file_icons/small/ttf.png'
vbs2_file: 'file_icons/small/vbs2.png'
vbs_file: 'file_icons/small/vbs.png'
warning_file: 'file_icons/small/warning.png'
wav_file: 'file_icons/small/wav.png'
zip2_file: 'file_icons/small/zip2.png'
genericBlue_file: 'file_icons/small/genericBlue.png'
genericGray_file: 'file_icons/small/genericGray.png'




aiff_file: 'file_icons/small/aiff.png' 
tmp_file: 'file_icons/small/tmp.png' 
mswmm_file: 'file_icons/small/mswmm.png' 
dvf_file: 'file_icons/small/dvf.png' 
m4p_file: 'file_icons/small/m4p.png' 
7z_file: 'file_icons/small/7z.png' 
wmv_file: 'file_icons/small/wmv.png' 
qxd_file: 'file_icons/small/qxd.png' 
ss_file: 'file_icons/small/ss.png' 
cdl_file: 'file_icons/small/cdl.png' 
log_file: 'file_icons/small/log.png' 
jar_file: 'file_icons/small/jar.png' 
divx_file: 'file_icons/small/divx.png' 
swf_file: 'file_icons/small/swf.png' 
asf_file: 'file_icons/small/asf.png' 
chm_file: 'file_icons/small/chm.png' 
bat_file: 'file_icons/small/bat.png' 
qbw_file: 'file_icons/small/qbw.png' 
rm_file: 'file_icons/small/rm.png' 
m4v_file: 'file_icons/small/m4v.png' 
ifo_file: 'file_icons/small/ifo.png' 
dmg_file: 'file_icons/small/dmg.png' 
cda_file: 'file_icons/small/cda.png' 
ram_file: 'file_icons/small/ram.png' 
cab_file: 'file_icons/small/cab.png' 
thm_file: 'file_icons/small/thm.png' 
wps_file: 'file_icons/small/wps.png' 
vob_file: 'file_icons/small/vob.png' 
qbb_file: 'file_icons/small/qbb.png' 
pub_file: 'file_icons/small/pub.png' 
dat_file: 'file_icons/small/dat.png' 
vcd_file: 'file_icons/small/vcd.png' 
ogg_file: 'file_icons/small/ogg.png' 
ptb_file: 'file_icons/small/ptb.png' 
jpeg_file: 'file_icons/small/jpeg.png' 
msi_file: 'file_icons/small/msi.png' 
bup_file: 'file_icons/small/bup.png' 
eml_file: 'file_icons/small/eml.png' 
m4b_file: 'file_icons/small/m4b.png' 
sea_file: 'file_icons/small/sea.png' 
ses_file: 'file_icons/small/ses.png' 
mpeg_file: 'file_icons/small/mpeg.png' 
htm_file: 'file_icons/small/htm.png' 
pst_file: 'file_icons/small/pst.png' 
cbr_file: 'file_icons/small/cbr.png' 
mdb_file: 'file_icons/small/mdb.png' 
amr_file: 'file_icons/small/amr.png' 
ace_file: 'file_icons/small/ace.png' 
torrent_file: 'file_icons/small/torrent.png' 
xpi_file: 'file_icons/small/xpi.png' 
ps_file: 'file_icons/small/ps.png' 
tgz_file: 'file_icons/small/tgz.png' 
sit_file: 'file_icons/small/sit.png' 
mcd_file: 'file_icons/small/mcd.png' 
m4a_file: 'file_icons/small/m4a.png' 
indd_file: 'file_icons/small/indd.png' 
sitx_file: 'file_icons/small/sitx.png' 
asx_file: 'file_icons/small/asx.png' 
cdr_file: 'file_icons/small/cdr.png' 
fla_file: 'file_icons/small/fla.png' 
flv_file: 'file_icons/small/flv.png' 
dss_file: 'file_icons/small/dss.png' 
mid_file: 'file_icons/small/mid.png' 
3gp_file: 'file_icons/small/3gp.png' 
lnk_file: 'file_icons/small/lnk.png' 
exe_file: 'file_icons/small/exe.png' 
iso_file: 'file_icons/small/iso.png' 
dwg_file: 'file_icons/small/dwg.png' 
rmvb_file: 'file_icons/small/rmvb.png' 
wma_file: 'file_icons/small/wma.png' 
