investigation_checksum: https://docs.seek4science.org/tech/investigation-checksum.html
roles: https://docs.seek4science.org/help/user-guide/roles.html
programme_self_management: https://docs.seek4science.org/help/user-guide/programme-creation-and-management.html
get_started: https://docs.seek4science.org/help/user-guide/index.html
get_involved: https://fair-dom.org/contribute/
registering: https://docs.seek4science.org/help/user-guide/registering.html
join_project: https://docs.seek4science.org/help/user-guide/request-to-join-project.html
credits: https://docs.seek4science.org/credits
admin_project_members: https://docs.seek4science.org/help/user-guide/administer-project-members.html
isa_overview: https://docs.seek4science.org/help/user-guide/isa-overview.html
null_license: https://choosealicense.com/no-permission/
data_file_wizard: https://docs.seek4science.org/help/user-guide/data-file-upload-wizard.html
dashboard: https://docs.seek4science.org/help/user-guide/project-dashboard.html
report_bugs_and_features: https://docs.seek4science.org/tech/reporting-bugs-and-features.html
Collection: https://docs.seek4science.org/help/user-guide/collections.html
Institution: https://docs.seek4science.org/help/user-guide/create-a-project.html
#Person: https://docs.seek4science.org/help/user-guide/registering.html
Programme: https://docs.seek4science.org/help/user-guide/create-a-project.html
Project: https://docs.seek4science.org/help/user-guide/create-a-project.html
Investigation: https://docs.seek4science.org/help/isa-guide.html
Study: https://docs.seek4science.org/help/isa-guide.html
Assay: https://docs.seek4science.org/help/isa-guide.html
DataFile: https://docs.seek4science.org/help/user-guide/general-attributes.html#data-files
Sop: https://docs.seek4science.org/help/user-guide/general-attributes.html#sops
Publication: https://docs.seek4science.org/help/user-guide/general-attributes.html#publications
Sample: https://docs.seek4science.org/help/user-guide/samples.html
SampleType: https://docs.seek4science.org/help/user-guide/create-sample-type.html
Organism: https://docs.seek4science.org/help/user-guide/general-attributes.html#organisms
Model: https://docs.seek4science.org/help/user-guide/adding-assets.html
Document: https://docs.seek4science.org/help/user-guide/adding-assets.html
Presentation: https://docs.seek4science.org/help/user-guide/adding-assets.html
Event: https://docs.seek4science.org/help/user-guide/general-attributes.html#events
clipboard_api_mozilla: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
