
---
help_attachments:
  columns:
  - id
  - help_document_id
  - title
  - content_type
  - filename
  - size
  - db_file_id
  - created_at
  - updated_at
  records: 
  - - 3
    - 13
    - Nature Protocols Format for SOPs
    - application/msword
    - NatureProtocolsFormat.doc
    - 24064
    - 5
    - 2010-09-08 13:11:19.000000000 Z
    - 2010-09-08 13:11:19.000000000 Z
  - - 5
    - 13
    - Intracellular metabolite mesurements
    - application/vnd.ms-excel
    - metabolites_intracellular.xls
    - 75776
    - 8
    - 2010-11-02 13:44:55.000000000 Z
    - 2010-11-02 13:44:55.000000000 Z
  - - 11
    - 13
    - Mass_Spec_JERM
    - application/vnd.ms-excel
    - JERM_priderf_SEEKJERM.xls
    - 115712
    - 15
    - 2012-03-29 11:39:12.000000000 Z
    - 2012-03-29 11:39:12.000000000 Z
  - - 12
    - 13
    - Gel_Electrophoresis
    - application/vnd.ms-excel
    - JERM_2DGel_SEEKJERM.xls
    - 88576
    - 16
    - 2012-03-29 11:50:35.000000000 Z
    - 2012-03-29 11:50:35.000000000 Z
  - - 19
    - 13
    - Gene Expression ArrayExpress
    - application/vnd.ms-excel
    - microarray_example_newformat.xls
    - 99328
    - 23
    - 2012-06-01 08:14:32.000000000 Z
    - 2012-06-01 08:14:32.000000000 Z
  - - 20
    - 13
    - General Chip-chip Array
    - application/vnd.ms-excel
    - GA_ChIP_chip_w_platf_SEEKJERM-1.xls
    - 105472
    - 24
    - 2012-06-01 08:22:54.000000000 Z
    - 2012-06-01 08:22:54.000000000 Z
  - - 21
    - 13
    - RT-PCR
    - application/vnd.ms-excel
    - GA_RT-PCR_SEEKJERM.xls
    - 114688
    - 25
    - 2012-06-01 08:26:17.000000000 Z
    - 2012-06-01 08:26:17.000000000 Z
  - - 22
    - 13
    - 3' or Whole Gene Expression array
    - application/vnd.ms-excel
    - Copy_of_GA_affy_SEEKJERM.xls
    - 130048
    - 26
    - 2012-06-01 08:30:15.000000000 Z
    - 2012-06-01 08:30:15.000000000 Z
  - - 23
    - 13
    - Chip-chip Array
    - application/vnd.ms-excel
    - GA_affy_genomic_BAR_SEEKJERM.xls
    - 151552
    - 27
    - 2012-06-01 08:35:28.000000000 Z
    - 2012-06-01 08:35:28.000000000 Z
  - - 24
    - 13
    - Gene Expression
    - application/vnd.ms-excel
    - GA_NG_genex_plat_SEEKJERM.xls
    - 148992
    - 28
    - 2012-06-01 08:38:00.000000000 Z
    - 2012-06-01 08:38:00.000000000 Z
  - - 26
    - 13
    - Master Template
    - application/excel
    - MASTER_exampleBlank2.xls
    - 95744
    - 30
    - 2013-06-07 12:45:44.000000000 Z
    - 2013-06-07 12:45:44.000000000 Z
