name: ansible-install
run-name: ${{ github.actor }} is testing Ansible install
on:
  workflow_dispatch:
jobs:
  install-seek-from-ansible:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04,ubuntu-22.04,ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure ansible for local install
        run: |
          sed -i '/vault_password_file/d' ansible.cfg
          sed -i '/ssh_connection/d' ansible.cfg
          sed -i '/pipelining/d' ansible.cfg
          sed -i 's/\- hosts\: \[servers\]/\- hosts\: localhost/g' Deploy-SEEK.yml
          sed -i '/\- hosts\: localhost/a \ \ connection\: local' Deploy-SEEK.yml
          sed -i 's/user_var\: francisco/user_var\: runner/' group_vars/vars.yml
          sed -i 's/git_dest\: \/home\/francisco/git_dest\: \/home\/runner\/work/' group_vars/vars.yml
          sed -i 's/sql_user\: francisco/sql_user\: mysqluser/' group_vars/vars.yml
          sed -i '/sql_user\: mysqluser/a sql_password: mysqlpassword' group_vars/vars.yml

      - name: Install SEEK through ansible
        run: ansible-playbook Deploy-SEEK.yml
